export const notificationTitles = [
  "📩 New message just dropped. Ama ni ghosting tena? 👻",
  "🚗 Matatu vibes loading… but first, check your message!",
  "🍗 Skip the kuku, your inbox is hotter 🔥",
  "🧃 Uko thirsty? Your chat buddy just quenched your inbox 💬",
  "😂 Someone just slid into your DMs. It’s not a prank, fr fr.",
  "🌍 Nairobi weather hot, but your message is hotter 😮‍💨",
  "📲 This one is louder than a TikTok mashup! Check it out.",
  "👀 Sema? New tea has been spilled in your inbox ☕️",
  "💌 Love letter? Nope. Just a chaotic new message 😜",
  "📥 Vibing? Someone’s tryna add to the mood. Check your inbox!",
  "🔥 This message is spicier than kachumbari 🌶️",
  "🤳 Your crush? Your ex? Only one way to find out...",
  "🎤 This chat is calling harder than a gengetone banger 🎶",
  "😅 Uko jobless ama busy? Doesn’t matter. Message imefika!",
  "📦 Forget deliveries. This is the message of the day 🛵",
  "🌚 Si you said you're done with talking? Message still landed 😏",
  "🧠 Kwani ulisahau you’re popular? New message just came in!",
  "🥴 Life is hard, but your inbox just got easier.",
  "🚨 Message alert! Might be drama, might be blessings 😂",
  "😈 Weekend plans pending? This message might just change that.",
  "🤔 Could be a job, a joke, or a jibu. Only one way to know.",
  "👑 They texted! Time to show them main character energy.",
  "🥶 That message is colder than Ngong Hills at 6am!",
  "📱 Message just vibed its way into your phone.",
  "💥 New message unlocked! Like a bonus level in life.",
  "🎯 This message came straight from the sauce department.",
  "💃 Your inbox is now grooving—someone texted!",
  "😂 Githeri or not, this message deserves a peek.",
  "🤖 AI did not send this, a real human did. Check it!",
  "👻 Ghosts do not text. But this one did. Spooky!",
  "🌍 Your inbox just got global. Check that message, citizen!"
];
